/**
 * generate-registry — composes installed plugins into the runtime.
 *
 * Scans `plugins/<dir>/manifest.json`, validates each via `@sovereignfs/manifest`,
 * writes the typed plugin registry to `runtime/generated/registry.ts`, and links
 * each plugin's `app/` into `runtime/app/plugins/<dir>/` — symlinks in dev,
 * copies in production (NODE_ENV). An invalid manifest fails the build.
 *
 * Run via `pnpm generate`; the runtime dev script runs it before `next dev`.
 * Pass `--watch` to re-run when plugin directories are added or removed.
 *
 * See: SRS §3.9 Plugin Loading Model.
 */
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  watch,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateManifest, type SovereignManifest } from '@sovereignfs/manifest';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PLUGINS_DIR = join(ROOT, 'plugins');
const RUNTIME_PLUGINS_DIR = join(ROOT, 'runtime', 'app', 'plugins');
const REGISTRY_FILE = join(ROOT, 'runtime', 'generated', 'registry.ts');

const isProd = process.env.NODE_ENV === 'production';

interface PluginEntry {
  dir: string;
  manifest: SovereignManifest;
}

function readPlugins(): PluginEntry[] {
  if (!existsSync(PLUGINS_DIR)) return [];
  const plugins: PluginEntry[] = [];

  for (const entry of readdirSync(PLUGINS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const manifestPath = join(PLUGINS_DIR, entry.name, 'manifest.json');
    if (!existsSync(manifestPath)) continue;

    let json: unknown;
    try {
      json = JSON.parse(readFileSync(manifestPath, 'utf8'));
    } catch (error) {
      console.error(
        `[generate] ${relative(ROOT, manifestPath)} is not valid JSON: ${(error as Error).message}`,
      );
      process.exit(1);
    }

    const result = validateManifest(json);
    if (!result.valid) {
      console.error(`[generate] invalid manifest ${relative(ROOT, manifestPath)}:`);
      for (const message of result.errors) console.error(`  - ${message}`);
      process.exit(1);
    }

    plugins.push({ dir: entry.name, manifest: result.manifest });
  }

  plugins.sort((a, b) => a.manifest.id.localeCompare(b.manifest.id));
  return plugins;
}

function writeRegistry(plugins: PluginEntry[]): void {
  mkdirSync(dirname(REGISTRY_FILE), { recursive: true });
  const manifests = plugins.map((p) => p.manifest);
  const content = `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit.
// Run \`pnpm generate\` to regenerate.
import type { SovereignManifest } from '@sovereignfs/manifest';

export const registry: SovereignManifest[] = ${JSON.stringify(manifests, null, 2)};
`;
  writeFileSync(REGISTRY_FILE, content);
}

function composePlugins(plugins: PluginEntry[]): void {
  mkdirSync(RUNTIME_PLUGINS_DIR, { recursive: true });

  // Remove previously composed plugins (keep the .gitignore).
  for (const entry of readdirSync(RUNTIME_PLUGINS_DIR)) {
    if (entry === '.gitignore') continue;
    rmSync(join(RUNTIME_PLUGINS_DIR, entry), { recursive: true, force: true });
  }

  for (const { dir } of plugins) {
    const srcApp = join(PLUGINS_DIR, dir, 'app');
    if (!existsSync(srcApp)) continue;
    const dest = join(RUNTIME_PLUGINS_DIR, dir);
    if (isProd) {
      cpSync(srcApp, dest, { recursive: true });
    } else {
      symlinkSync(srcApp, dest, 'dir');
    }
  }
}

function generate(): void {
  const plugins = readPlugins();
  writeRegistry(plugins);
  composePlugins(plugins);
  console.log(
    `[generate] ${String(plugins.length)} plugin(s) composed (${isProd ? 'copy' : 'symlink'}).`,
  );
}

generate();

if (process.argv.includes('--watch')) {
  console.log('[generate] watching plugins/ for changes…');
  let timer: NodeJS.Timeout | undefined;
  watch(PLUGINS_DIR, { recursive: true }, () => {
    clearTimeout(timer);
    timer = setTimeout(generate, 150);
  });
}
