import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { getSidebarApps } from "../src/launcher";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sidebarApps = getSidebarApps();

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <aside>
          <strong>Sovereign</strong>

          <nav>
            {sidebarApps.map((app) => (
              <a key={app.id} href={app.launch.path}>
                {app.name}
              </a>
            ))}
          </nav>
        </aside>

        {children}
      </body>
    </html>
  );
}